theme = "gruvbox_light_soft"

[keys.insert]
esc = ["move_char_left", "normal_mode"]

[editor]
shell = ["nu", "-c"]

[keys.normal.space.i]
a   = [":insert-output echo 'α'"]
b   = [":insert-output echo 'β'"]
y   = [":insert-output echo 'γ'"]
'[' = [":insert-output echo '⟨'"]
']' = [":insert-output echo '⟩'"]
'.' = [":insert-output echo '⋅'"]
x   = [":insert-output echo '×'"]

