[[language]]
name = "rust"
auto-format = false
formatter = { command = "rustfmt" }

[[language]]
name = "zig"
auto-format = false

[[language]]
name = "go"
auto-format = false

[[language]]
name = "c"
auto-format = false

[[language]]
name = "lean"
scope = "source.lean"
file-types = ["lean"]
auto-format = false

[language-server.lean]
command = "lean"
args = ["--server"]

# [language.debugger]
# name = "lldb-vscode"
# transport = "stdio"

# [[language.debugger.templates]]
# name = "binary (terminal)"
# request = "launch"
# completion = [ { name = "binary", completion = "filename" } ]
# args = { runInTerminal = true, program = "{0}" }

[[language]]
name = "odin"
auto-format = false
